$(document).ready(function(){
    $(function(){
        $("html, body").animate({ scrollTop: 0 },0); 
    });
    function $logo_ani(){
        $('.logo').animate({'marginLeft':'-5px'},200,function(){
            $('.logo').animate({'marginLeft':'0'},200);
        });
    }
    var $logo_timer = 0;
    function $run_logo(){
        $logo_timer = window.setInterval($logo_ani,1000);
    }
    $run_logo();
    $('.logo').on(
        'mouseenter',function(){
            $('.sub_gnb').stop(true).animate({'marginLeft':0},500);
            $(this).animate({'marginLeft':'0'},200);
            window.clearInterval($logo_timer);
        });
    $('.sub_gnb_wrap').on(
        'mouseleave',function(){
            $(this).find('.sub_gnb').animate({'marginLeft':'-515px'},400);
        });
    $('.header').on(
        'mouseleave',function(){
            $('.sub_gnb').animate({'marginLeft':'-515px'},400);
            $run_logo();
        });
    $('.left_container').on(
        'click',function(){
            $('.header_con').stop(true).animate({'left':'0'},500,function(){
                $('.header_con').find('li:last-child').prependTo('.header_con');
                $('.header_con').css({'left':'-100%'});
            });
        }).on(
            'mouseenter',function(){
                $('.movie_left').fadeOut(0);
                $('.movie_right').fadeOut(0);
            }).on(
                'mouseleave',function(){
                    $('.movie_left').fadeIn(0);
                    $('.movie_right').fadeIn(0);
                });
    $('.right_container').on(
        'click',function(){
            $('.header_con').stop(true).animate({'left':'-200%'},500,function(){
                $('.header_con').find('li:first-child').appendTo('.header_con');
                $('.header_con').css({'left':'-100%'});
            });
        }).on(
            'mouseenter',function(){
                $('.movie_left').fadeOut(0);
                $('.movie_right').fadeOut(0);
            }).on(
                'mouseleave',function(){
                    $('.movie_left').fadeIn(0);
                    $('.movie_right').fadeIn(0);
                });
    $('.gnb').find('li').on(
        'mouseenter',function(){
            $('.sub').stop(true).slideDown(300);
        });
    $('.gnb').on(
        'mouseleave',function(){
            $('.sub').stop(true).slideUp(300);
        });
    var $contentshere = $('#contents').offset().top;
    var $box_here = parseInt($contentshere)-300;
    var $box_fade_zone = parseInt($contentshere)+200;
    var $event_fade_zone = parseInt($contentshere)+600;
    var $other_fade_zone = parseInt($contentshere)+1000;
    // here = parseInt(here)-500;
    $(function() {
        $(window).scroll(function() {
            if ($(this).scrollTop() >= Math.ceil($box_here)) {
                $('.sub_gnb_wrap').fadeOut(0);
                $('.gnb').fadeOut(0);
                $('.p_logo').fadeIn(0);
                $('.logo').fadeOut(0);
                }else if($(this).scrollTop()< Math.ceil($box_here)){
                    $('.sub_gnb_wrap').fadeIn(0);
                    $('.gnb').fadeIn(0);
                    $('.p_logo').fadeOut(0);
                    $('.logo').fadeIn(0);
                }
            if($(this).scrollTop() >= Math.ceil($box_here)){
                $('.c_title').animate({'opacity':'1'},500,function(){
                    $('.box_office_wrap').animate({'opacity':'1'},500);
                });
            };
            if($(this).scrollTop()>=Math.ceil($box_fade_zone)){
                $('.shortcut_wrap').animate({'opacity':1},700);
            };
            if($(this).scrollTop()>=Math.ceil($event_fade_zone)){
                $('.event_wrap').animate({'opacity':1},700);
            };  
            if($(this).scrollTop()>=Math.ceil($other_fade_zone)){
                $('.other_banner_wrap').animate({'opacity':1},700);
            };  
            });
        });
    $('.box_left').on(
        'click',function(){
            $('.box_office').find('li').eq(0).fadeOut(0,function(){
                $('.box_office').find('li').eq(5).stop(true).animate({
                    'width':'246','height':'343','top':'126.5','left':'16%'
                },0);
                $('.box_office').find('li').eq(6).stop(true).animate({
                    'width':'246','height':'343','top':'126.5','left':'16%'
                },0);
                $('.box_office').find('li').eq(0).stop(true).animate({
                    'top':'126.5','left':'16%','width':'246','height':'343'
                },300);
                $('.box_office').find('li').eq(1).stop(true).animate({
                    'width':'246','height':'343','top':'126.5','left':'63%'
                },300);
                $('.box_office').find('li').eq(2).stop(true).animate({
                    'width':'335','height':'467','top':'64.5','left':'50%'
                },300,function(){
                    $(this).find('.boxoffice_shadow').stop(true).animate({'opacity':0},0)
                });
                $('.box_office').find('li').eq(3).stop(true).animate({
                    'width':'428','height':'596','top':'0','left':'33%'
                },300,function(){
                    $(this).find('.boxoffice_shadow').stop(true).animate({'opacity':1},0)
                });
                $('.box_office').find('li').eq(4).stop(true).animate({
                    'width':'335','height':'467','top':'64.5','left':'22%'
                },300);
                $('.box_office').find('li').eq(0).appendTo('.box_office')
                $('.box_office').find('li').eq(4).fadeIn(300);
            })
        });
    $('.box_right').on(
        'click',function(){
            $('.box_office').find('li').eq(4).fadeOut(0,function(){
                $('.box_office').find('li').eq(5).stop(true).animate({
                    'width':'246','height':'343','top':'126.5','left':'63%'
                },0);
                $('.box_office').find('li').eq(6).stop(true).animate({
                    'width':'246','height':'343','top':'126.5','left':'63%'
                },0);
                $('.box_office').find('li').eq(0).stop(true).animate({
                    'top':'64.5','left':'50%','width':'335','height':'467'
                },300);
                $('.box_office').find('li').eq(1).stop(true).animate({
                    'width':'428','height':'596','top':'0','left':'33%'
                },300,function(){
                    $(this).find('.boxoffice_shadow').stop(true).animate({'opacity':1},0)
                });
                $('.box_office').find('li').eq(2).stop(true).animate({
                    'width':'335','height':'467','top':'64.5','left':'22%'
                },300,function(){
                    $(this).find('.boxoffice_shadow').stop(true).animate({'opacity':0},0)
                });
                $('.box_office').find('li').eq(3).stop(true).animate({
                    'width':'246','height':'343','top':'126.5','left':'16%'
                },300);
                $('.box_office').find('li').eq(4).stop(true).animate({
                    'width':'246','height':'343','top':'126.5','left':'63%'
                },300);
                $('.box_office').find('li:last-child').prependTo('.box_office')
                $('.box_office').find('li').eq(0).fadeIn(300);
            })
        });
    $('.box_office').find('li').on(
        'mouseenter',function(){
            $(this).find('.boxoffice_shadow').stop(true).animate({'marginTop':'0'},300);
        }).on(
            'mouseleave',function(){
                $(this).find('.boxoffice_shadow').stop(true).animate({'marginTop':'-596px'},300);
            });
    $('.refresh').on(
        'click',function(){
            $('.move_img').stop(true).fadeOut(0,function(){
                $('.move_img').find('li').eq(0).appendTo('.move_img');
                $('.move_img').css({'left':'614px'});
                $('.move_img').stop(true).fadeIn(500);
                $('.move_img').stop(true).animate({'left':'269'},500);
            })
            $('.move_text').stop(true).fadeOut(0,function(){
                $('.move_text').find('li').eq(0).appendTo('.move_text');
                $('.move_text').css({'top':'377px'});
                $('.move_text').stop(true).fadeIn(500);
                $('.move_text').stop(true).animate({'top':'190'},500);
            })
            $('.mini_inner1').stop(true).fadeOut(0,function(){
                $('.mini_inner1').find('li').eq(0).appendTo('.mini_inner1');
                $('.mini_inner1').css({'left':'288px'});
                $('.mini_inner1').stop(true).fadeIn(500);
                $('.mini_inner1').stop(true).animate({'left':'0'},500);
            })
            $('.mini_inner2').stop(true).fadeOut(0,function(){
                $('.mini_inner2').find('li').eq(0).appendTo('.mini_inner2');
                $('.mini_inner2').css({'left':'288px'});
                $('.mini_inner2').stop(true).fadeIn(500);
                $('.mini_inner2').stop(true).animate({'left':'0'},500);
            })
        });
});
