$(document).ready(function(){
    $('.top_header_content>button').on(
        'click',function(){
            $('#top_header').slideUp(200);
        });
    $('.sns_wrap>li').on(
        'mouseenter',function(){
            $(this).find('a').find('img:nth-child(2)').stop(true).fadeOut(100);
    }).on(
        'mouseleave',function(){
        $(this).find('a').stop(true).find('img:nth-child(2)').fadeIn(100);
    });
    $('.gnb>li:nth-child(1)').on(
        'mouseenter',function(){
        $(this).find('a').find('p:nth-child(1)').find('img:nth-child(2)').fadeOut(200);
    }).on(
        'mouseleave',function(){
            $(this).find('a').find('p:nth-child(1)').find('img:nth-child(2)').fadeIn(200);
        });
    $('.gnb>li').on(
        'mouseenter',function(){
            $(this).find('ul').stop(true).slideDown(200);
        }).on('mouseleave',function(){
            $(this).find('ul').stop(true).slideUp(200);
        });
    $('.arcodian').on(
        'click',function(){
            $(this).toggleClass('open1')
            if($(this).hasClass('open1')){
                $('.arcodian_wrap').slideDown(200);
            }else{
                $('.arcodian_wrap').slideUp(200);
            }
        });
    $('.arcodian_title').find('li').on(
        'click',function(){
            $('.mcategory').fadeOut(0);
            $('.'+$(this).attr('data-tab')).fadeIn(0);
            $('.arcodian_title').find('li').removeClass('mhere');
            $(this).addClass('mhere');
        })
    $('.user_wrap').find('button').eq(0).on(
        'click',function(){
           $(this).toggleClass('searchopen')
           if($(this).hasClass('searchopen')){
            $('.msearch_wrap').fadeIn(100);
            $('.msearch_wrap').animate({'left':'6%'},300)
            $(this).find('img').attr('src','img/icon/mxbutton.png').animate({'marginTop':'60px'})
           }else{
               $('.msearch_wrap').fadeOut(0);
               $('.msearch_wrap').animate({'left':'18%'},300)
                $(this).find('img').attr('src','img/icon/searchmedia.png').animate({'marginTop':'0'})
           }
        });
    $('.product').on(
        'mouseenter',function(){
            $(this).find('.product_hover').find('button').stop(true).animate({
                'marginTop':'40px'
            },200)
            $(this).find('.product_hover').stop(true).animate({
                'top':'140px'
            },200);
        }).on(
            'mouseleave',function(){
                $(this).find('.product_hover').find('button').stop(true).animate({
                    'marginTop':'140px'
                },200)
                $(this).find('.product_hover').stop(true).animate({
                    'top':'280px'
                },200);
            });
    $('.product_hover').find('button:nth-child(1)').on(
        'mouseenter',function(){
            $(this).find('img').stop(true).attr('src','img/icon/subsearchbuttonhover.png')
        }).on(
            'mouseleave',function(){
              $(this).find('img').stop(true).attr('src','img/icon/subsearchbutton.png')  
            });
    $('.product_hover').find('button:nth-child(2)').on(
            'mouseenter',function(){
            $(this).find('img').stop(true).attr('src','img/icon/carthover.png')
        }).on(
            'mouseleave',function(){
              $(this).find('img').stop(true).attr('src','img/icon/cart.png')  
            });
    $('.m_open_button').find('button').on(
        'click',function(){
            $('.product_tap_wrap').find('div:nth-child(n+9):nth-child(-n+16)').slideDown(300);
            if($(this).hasClass('open_product')){
                $('.product_tap_wrap').find('div:nth-child(n+17)').slideDown(300);
                $(this).removeClass('open_product')
            }else{
                $(this).addClass('open_product')
            }
        })
});